# Generated by Django 5.2.8 on 2025-11-27 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('entity_type', models.TextField(choices=[('account', 'Account'), ('contact', 'Contact'), ('product', 'Product'), ('order', 'Sales Order'), ('ticket', 'Ticket'), ('project', 'Project')])),
                ('entity_id', models.CharField(max_length=255)),
                ('entity_title', models.TextField()),
                ('entity_subtitle', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.user')),
            ],
            options={
                'db_table': 'favorites',
                'unique_together': {('user', 'entity_type', 'entity_id')},
            },
        ),
    ]
