# Generated by Django 5.2.8 on 2025-11-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_favorite_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='azure_ad_object_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='azure_ad_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('admin', 'Administrator'), ('finance', 'Finance'), ('hr', 'HR Manager'), ('operations', 'Operations'), ('site_manager', 'Site Manager'), ('executive', 'Executive'), ('user', 'User')], default='user'),
        ),
    ]
