# Generated by Django 5.2.8 on 2025-11-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_azure_ad_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_account_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_project_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_warehouse_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.TextField(choices=[('internal', 'Internal Staff'), ('external', 'External User')], default='internal'),
        ),
        migrations.AddField(
            model_name='user',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('system_admin', 'System Administrator'), ('finance_manager', 'Finance Manager'), ('sales_rep', 'Sales Representative'), ('operations_specialist', 'Operations Specialist'), ('site_manager', 'Site Manager'), ('hr_specialist', 'HR Specialist'), ('warehouse_clerk', 'Warehouse Clerk'), ('field_worker', 'Field Worker'), ('subcontractor', 'Subcontractor/Vendor'), ('client', 'Client/Customer'), ('executive', 'Executive Viewer')], default='field_worker'),
        ),
    ]
