# Generated by Django 5.2.8 on 2025-11-27 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('crm', '0001_initial'),
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('status', models.TextField()),
                ('location', models.TextField()),
                ('next_service', models.TextField()),
                ('image_url', models.TextField(blank=True, null=True)),
                ('serial_number', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(db_column='assigned_to_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.employee')),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.warehouse')),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('status', models.TextField()),
                ('progress', models.IntegerField(default=0)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.account')),
                ('manager', models.ForeignKey(db_column='manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('size', models.TextField()),
                ('author', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('project', models.ForeignKey(db_column='project_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.project')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='SafetyInspection',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('site', models.TextField()),
                ('type', models.TextField()),
                ('status', models.TextField()),
                ('inspector', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('findings', models.TextField(blank=True, null=True)),
                ('corrective_actions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(db_column='project_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.project')),
            ],
            options={
                'db_table': 'safety_inspections',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.TextField()),
                ('category', models.TextField(blank=True, null=True)),
                ('type', models.TextField(default='expense')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(db_column='project_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.project')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
