# Generated by Django 5.2.8 on 2025-11-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual cost to date', max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='next_milestone_date',
            field=models.DateField(blank=True, help_text='Date of next project milestone', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='next_milestone_name',
            field=models.TextField(blank=True, help_text='Name of next project milestone', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='planned_progress',
            field=models.IntegerField(default=0, help_text='Expected progress percentage based on schedule'),
        ),
    ]
