# Generated by Django 5.2.8 on 2025-11-27 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_accounts', to='core.user'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='account',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='fax',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='legal_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to='crm.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_terms',
            field=models.TextField(choices=[('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('due_on_receipt', 'Due on Receipt'), ('custom', 'Custom')], default='net_30'),
        ),
        migrations.AddField(
            model_name='account',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='tier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='vat_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='street2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='do_not_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_opt_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='preferred_communication',
            field=models.TextField(choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('mail', 'Mail')], default='email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter_handle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_accounts', to='core.user'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.TextField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('partner', 'Partner'), ('prospect', 'Prospect')], default='customer'),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.TextField(choices=[('billing', 'Billing'), ('shipping', 'Shipping'), ('mailing', 'Mailing'), ('headquarters', 'Headquarters'), ('branch', 'Branch')], default='billing'),
        ),
    ]
