# Generated by Django 5.2.8 on 2025-11-27 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('room_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('direct', 'Direct Message'), ('project', 'Project')], default='public', max_length=20)),
                ('project_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'chat_rooms',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['room_type'], name='chat_rooms_room_ty_c8c67a_idx'), models.Index(fields=['is_archived'], name='chat_rooms_is_arch_2be36b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_id', models.CharField(db_index=True, max_length=255)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('system', 'System'), ('file', 'File')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('attachment_url', models.URLField(blank=True, null=True)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('attachment_type', models.CharField(blank=True, max_length=100)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('emoji', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.message')),
            ],
            options={
                'db_table': 'chat_message_reactions',
            },
        ),
        migrations.CreateModel(
            name='RoomMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.chatroom')),
            ],
            options={
                'db_table': 'chat_room_memberships',
            },
        ),
        migrations.CreateModel(
            name='TypingIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_users', to='chat.chatroom')),
            ],
            options={
                'db_table': 'chat_typing_indicators',
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'created_at'], name='chat_messag_room_id_cc7f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_id'], name='chat_messag_sender__e8b05b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['parent_message'], name='chat_messag_parent__f12578_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'user_id', 'emoji')},
        ),
        migrations.AddIndex(
            model_name='roommembership',
            index=models.Index(fields=['user_id', 'room'], name='chat_room_m_user_id_4d45e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roommembership',
            unique_together={('room', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='typingindicator',
            unique_together={('room', 'user_id')},
        ),
    ]
