# Generated by Django 5.2.8 on 2025-11-27 15:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_id', models.CharField(db_index=True, max_length=255)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('system', 'System')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('attachment_url', models.URLField(blank=True, null=True)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('attachment_type', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_dm_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectMessageThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user1_id', models.CharField(db_index=True, max_length=255)),
                ('user1_name', models.CharField(blank=True, max_length=255)),
                ('user1_email', models.EmailField(blank=True, max_length=254)),
                ('user2_id', models.CharField(db_index=True, max_length=255)),
                ('user2_name', models.CharField(blank=True, max_length=255)),
                ('user2_email', models.EmailField(blank=True, max_length=254)),
                ('user1_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('user2_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.directmessage')),
            ],
            options={
                'db_table': 'chat_dm_threads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='directmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.directmessagethread'),
        ),
        migrations.AddIndex(
            model_name='directmessagethread',
            index=models.Index(fields=['user1_id', 'user2_id'], name='chat_dm_thr_user1_i_26bc78_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessagethread',
            index=models.Index(fields=['user2_id', 'user1_id'], name='chat_dm_thr_user2_i_7c652a_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['thread', 'created_at'], name='chat_dm_mes_thread__317862_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['sender_id'], name='chat_dm_mes_sender__96bebd_idx'),
        ),
    ]
